## Programming for Analytics asignment
Mary McHale

The assignment is based on using the numpy.random package in Python.

#### Purpose of the package
Numpy is the primary package used for performing scientific calculations(e.g. the generation of random numbers, linear algebra) and data analysis in Python. The Numpy name is short for Numerical Python. NumPy includes:

 - Standard mathematical functions (e.g. addition, subtraction, multiplication and division) for quick calculations on entire arrays of data. The advantage of NumPy is that it has functions to do this in one step, otherwise Python could only perform this by using loops and for large data, this would use up a lot of memory and time to get the required result.
 
 - ndarray, a key feature, a fast and adaptable container for large data sets in Python where 'nd' denotes the dimension size.
 
 - NumPy can be used with other Python packages quite eaasily for higher level data analytical functionality
References : 
https://www.oreilly.com/library/view/python-for-data/9781449323592/ch04.html
http://numba.pydata.org/numba-doc/0.19.1/reference/numpysupported.html
http://cs231n.github.io/python-numpy-tutorial/
file:///C:/Users/Mary/Downloads/Numpy.pdf

#### Explanation of the function 'simple random data'.

The purpose of the 'simple random data' function is to produce a sample from a larger set of data where all data points are equal and have the same chance of being selected. 
https://www.investopedia.com/terms/s/simple-random-sample.asp

There are ten types of functions in NumPy to create 'simple random data', each with diferent purposes. Of these, I will explain the following 3 - randint(), rand() and randn().

Reference : https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.normal.html

In [5]:
## randint() function

# the number '10' below is to use the numbers 0 to 9 as the data range from which to produce the random numbers
# size relates to the number of random numbers to generate.
np.random.randint(10, size=5)


array([2, 9, 9, 1, 4])

In [12]:
## rand() function : Returns random numbers which are only in the range 0 to 1 in a given shape
print(np.random.rand())

# To get results in a 2*3 matrix format, then need to add in the rgument '(2,3)' to the function for this example. 
print(np.random.rand(2,3))

# The function randn() generates returns random numbers which are only in the range 0 to 1 in a given shape plus the numbers follow in a simple normal distribution.
# Note a minus number is now included as a result.
print(np.random.randn(2,3))

0.44963751510721683
[[ 0.53073371  0.26882054  0.52917205]
 [ 0.04963564  0.74549298  0.63425905]]
[[-0.2276696   0.66863859  0.23710185]
 [-0.03778353 -0.21014137 -0.20588065]]


#### Explanation of the function 'permutations'.
The function 'permutation' calculates the number of combinations for a given range of numbers, for example 0 to 10 which will have 100 combinations (10x10) and returns one of the combinations which it has randomly selected. This output would be the same every time for a pre-defined array.

The 'shuffle' function is included as part of the 'permutation' function but it can also be used separately to mix up a pre ordered list of data and would return different values for a pre-defined array. The shefle function works on pre-defined arrays.
Reference : https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.permutation.html

In [13]:
# Permutation function
np.random.permutation(10)
 

array([4, 9, 7, 0, 8, 1, 6, 2, 5, 3])

In [26]:
# Shuffle function
# 1st need to specify an array

array = [0,1,2,3,4,5,6,7,8,9]
np.random.shuffle(array)
print(array)

[3, 8, 9, 2, 6, 0, 5, 4, 1, 7]


 #### Explain the use and purposes of at least 5 'Distributions' functions
 - (1) Normal, called standard Normal
 - (2) Exponential
 - (3) Binomial
 - (4) Geometric
 - (5) Chi-squared
 
 
 

#### Explain the use of seeds in generating pseudorandom numbers.
when dont use permutations cos want the same number ????????
 

### Importing the required libraries
First, import the Numpy package 

In [1]:
import numpy as np